# Add configuration values here, as shown below.
#
# pusher_app_id: "2954"
# pusher_key: 7381a978f7dd7f9a1117
# pusher_secret: abdc3b896a0ffb85d373
# stripe_api_key: sk_test_2J0l093xOyW72XUYJHE4Dv2r
# stripe_publishable_key: pk_test_ro9jV5SNwGb1yYlQfzG17LHK

  password: 'onozorgheneho'
  email: 'alex.obogbare@gmail.com'
  FACEBOOK_APP_ID: "484766111702543"
  FACEBOOK_APP_SECRET: '73fe45582ab2101860d6b8972c3bc228'
  GOOGLE_APP_ID: '355480203843-5h4kfo0v0loovrdr64jviup2dr4sg5jc.apps.googleusercontent.com'
  GOOGLE_APP_SECRET: 'XSLfIHYxgMvyNgcG09tQg_CT'
  API_KEY: '0syfAluwvgax4wUlPjb0sHWMy'
  API_SECRET: 'uC0HCPEnDRA9ghezZiIYyJtVBkhWmONw7DG13jXM6p3pzTOUbG'
  LINKEDIN_KEY: '77uxkj9x63ifxh'
  LINKEDIN_SECRET: 'plRxlF1mxgeZE876'
