development:
  cloud_name: 'sportbay-co'
  api_key: '196782493197544'
  api_secret: 0n2TqFHsWt0UbPIvTLcGuVvPnno
  enhance_image_tag: true
  static_image_support: false
production:
  cloud_name: 'sportbay-co'
  api_key: '196782493197544'
  api_secret: "0n2TqFHsWt0UbPIvTLcGuVvPnno"
  enhance_image_tag: true
  static_image_support: true
test:
  cloud_name: 'sportbay-co'
  api_key: '196782493197544'
  api_secret: "0n2TqFHsWt0UbPIvTLcGuVvPnno"
  enhance_image_tag: true
  static_image_support: false